# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/MiniZed_constraints.xdc

# Block Designs: bd/PS_DRAM_BD/PS_DRAM_BD.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PS_DRAM_BD || ORIG_REF_NAME==PS_DRAM_BD} -quiet] -quiet

# IP: bd/PS_DRAM_BD/ip/PS_DRAM_BD_processing_system7_0_0/PS_DRAM_BD_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PS_DRAM_BD_processing_system7_0_0 || ORIG_REF_NAME==PS_DRAM_BD_processing_system7_0_0} -quiet] -quiet

# Block Designs: bd/PL_BRAM_BD/PL_BRAM_BD.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PL_BRAM_BD || ORIG_REF_NAME==PL_BRAM_BD} -quiet] -quiet

# IP: bd/PL_BRAM_BD/ip/PL_BRAM_BD_processing_system7_0_0/PL_BRAM_BD_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PL_BRAM_BD_processing_system7_0_0 || ORIG_REF_NAME==PL_BRAM_BD_processing_system7_0_0} -quiet] -quiet

# Block Designs: bd/PL_LUT_BD/PL_LUT_BD.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PL_LUT_BD || ORIG_REF_NAME==PL_LUT_BD} -quiet] -quiet

# IP: bd/PL_LUT_BD/ip/PL_LUT_BD_processing_system7_0_0/PL_LUT_BD_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PL_LUT_BD_processing_system7_0_0 || ORIG_REF_NAME==PL_LUT_BD_processing_system7_0_0} -quiet] -quiet

# Block Designs: bd/PS_BRAM_BD/PS_BRAM_BD.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PS_BRAM_BD || ORIG_REF_NAME==PS_BRAM_BD} -quiet] -quiet

# IP: bd/PS_BRAM_BD/ip/PS_BRAM_BD_axi_bram_ctrl_0_0/PS_BRAM_BD_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PS_BRAM_BD_axi_bram_ctrl_0_0 || ORIG_REF_NAME==PS_BRAM_BD_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/PS_BRAM_BD/ip/PS_BRAM_BD_axi_bram_ctrl_1_0/PS_BRAM_BD_axi_bram_ctrl_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PS_BRAM_BD_axi_bram_ctrl_1_0 || ORIG_REF_NAME==PS_BRAM_BD_axi_bram_ctrl_1_0} -quiet] -quiet

# IP: bd/PS_BRAM_BD/ip/PS_BRAM_BD_axi_interconnect_0_0/PS_BRAM_BD_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PS_BRAM_BD_axi_interconnect_0_0 || ORIG_REF_NAME==PS_BRAM_BD_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/PS_BRAM_BD/ip/PS_BRAM_BD_axi_interconnect_1_0/PS_BRAM_BD_axi_interconnect_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PS_BRAM_BD_axi_interconnect_1_0 || ORIG_REF_NAME==PS_BRAM_BD_axi_interconnect_1_0} -quiet] -quiet

# IP: bd/PS_BRAM_BD/ip/PS_BRAM_BD_blk_mem_gen_0_0/PS_BRAM_BD_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PS_BRAM_BD_blk_mem_gen_0_0 || ORIG_REF_NAME==PS_BRAM_BD_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/PS_BRAM_BD/ip/PS_BRAM_BD_processing_system7_0_0/PS_BRAM_BD_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PS_BRAM_BD_processing_system7_0_0 || ORIG_REF_NAME==PS_BRAM_BD_processing_system7_0_0} -quiet] -quiet

# IP: bd/PS_BRAM_BD/ip/PS_BRAM_BD_rst_ps7_0_50M_0/PS_BRAM_BD_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PS_BRAM_BD_rst_ps7_0_50M_0 || ORIG_REF_NAME==PS_BRAM_BD_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/PS_BRAM_BD/ip/PS_BRAM_BD_auto_pc_0/PS_BRAM_BD_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PS_BRAM_BD_auto_pc_0 || ORIG_REF_NAME==PS_BRAM_BD_auto_pc_0} -quiet] -quiet

# IP: bd/PS_BRAM_BD/ip/PS_BRAM_BD_auto_pc_1/PS_BRAM_BD_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PS_BRAM_BD_auto_pc_1 || ORIG_REF_NAME==PS_BRAM_BD_auto_pc_1} -quiet] -quiet

# XDC: bd/PS_DRAM_BD/PS_DRAM_BD_ooc.xdc

# XDC: bd/PL_BRAM_BD/PL_BRAM_BD_ooc.xdc

# XDC: bd/PL_LUT_BD/PL_LUT_BD_ooc.xdc

# XDC: bd/PS_BRAM_BD/PS_BRAM_BD_ooc.xdc
