# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 2
create_project -in_memory -part xc7z007sclg225-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/aptsi/Desktop/FIFO_MiniZed/FIFO_MiniZed.cache/wt [current_project]
set_property parent.project_path C:/Users/aptsi/Desktop/FIFO_MiniZed/FIFO_MiniZed.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:minized:part0:1.2 [current_project]
set_property ip_output_repo c:/Users/aptsi/Desktop/FIFO_MiniZed/FIFO_MiniZed.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/aptsi/Desktop/FIFO_MiniZed/FIFO_MiniZed.srcs/sources_1/new/PL_BRAM.v
  C:/Users/aptsi/Desktop/FIFO_MiniZed/FIFO_MiniZed.srcs/sources_1/new/PL_BRAM_wrapper.v
  C:/Users/aptsi/Desktop/FIFO_MiniZed/FIFO_MiniZed.srcs/sources_1/new/PL_LUT.v
  C:/Users/aptsi/Desktop/FIFO_MiniZed/FIFO_MiniZed.srcs/sources_1/new/PL_LUT_wrapper.v
  C:/Users/aptsi/Desktop/FIFO_MiniZed/FIFO_MiniZed.srcs/sources_1/new/PS_BRAM_wrapper.v
  C:/Users/aptsi/Desktop/FIFO_MiniZed/FIFO_MiniZed.srcs/sources_1/new/PS_DRAM_wrapper.v
  C:/Users/aptsi/Desktop/FIFO_MiniZed/FIFO_MiniZed.srcs/sources_1/new/FIFO.v
}
add_files C:/Users/aptsi/Desktop/FIFO_MiniZed/FIFO_MiniZed.srcs/sources_1/bd/PS_DRAM_BD/PS_DRAM_BD.bd
set_property used_in_implementation false [get_files -all c:/Users/aptsi/Desktop/FIFO_MiniZed/FIFO_MiniZed.srcs/sources_1/bd/PS_DRAM_BD/ip/PS_DRAM_BD_processing_system7_0_0/PS_DRAM_BD_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all C:/Users/aptsi/Desktop/FIFO_MiniZed/FIFO_MiniZed.srcs/sources_1/bd/PS_DRAM_BD/PS_DRAM_BD_ooc.xdc]

add_files C:/Users/aptsi/Desktop/FIFO_MiniZed/FIFO_MiniZed.srcs/sources_1/bd/PL_BRAM_BD/PL_BRAM_BD.bd
set_property used_in_implementation false [get_files -all c:/Users/aptsi/Desktop/FIFO_MiniZed/FIFO_MiniZed.srcs/sources_1/bd/PL_BRAM_BD/ip/PL_BRAM_BD_processing_system7_0_0/PL_BRAM_BD_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all C:/Users/aptsi/Desktop/FIFO_MiniZed/FIFO_MiniZed.srcs/sources_1/bd/PL_BRAM_BD/PL_BRAM_BD_ooc.xdc]

add_files C:/Users/aptsi/Desktop/FIFO_MiniZed/FIFO_MiniZed.srcs/sources_1/bd/PL_LUT_BD/PL_LUT_BD.bd
set_property used_in_implementation false [get_files -all c:/Users/aptsi/Desktop/FIFO_MiniZed/FIFO_MiniZed.srcs/sources_1/bd/PL_LUT_BD/ip/PL_LUT_BD_processing_system7_0_0/PL_LUT_BD_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all C:/Users/aptsi/Desktop/FIFO_MiniZed/FIFO_MiniZed.srcs/sources_1/bd/PL_LUT_BD/PL_LUT_BD_ooc.xdc]

add_files C:/Users/aptsi/Desktop/FIFO_MiniZed/FIFO_MiniZed.srcs/sources_1/bd/PS_BRAM_BD/PS_BRAM_BD.bd
set_property used_in_implementation false [get_files -all c:/Users/aptsi/Desktop/FIFO_MiniZed/FIFO_MiniZed.srcs/sources_1/bd/PS_BRAM_BD/ip/PS_BRAM_BD_axi_bram_ctrl_0_0/PS_BRAM_BD_axi_bram_ctrl_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptsi/Desktop/FIFO_MiniZed/FIFO_MiniZed.srcs/sources_1/bd/PS_BRAM_BD/ip/PS_BRAM_BD_axi_bram_ctrl_1_0/PS_BRAM_BD_axi_bram_ctrl_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptsi/Desktop/FIFO_MiniZed/FIFO_MiniZed.srcs/sources_1/bd/PS_BRAM_BD/ip/PS_BRAM_BD_blk_mem_gen_0_0/PS_BRAM_BD_blk_mem_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptsi/Desktop/FIFO_MiniZed/FIFO_MiniZed.srcs/sources_1/bd/PS_BRAM_BD/ip/PS_BRAM_BD_processing_system7_0_0/PS_BRAM_BD_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptsi/Desktop/FIFO_MiniZed/FIFO_MiniZed.srcs/sources_1/bd/PS_BRAM_BD/ip/PS_BRAM_BD_rst_ps7_0_50M_0/PS_BRAM_BD_rst_ps7_0_50M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptsi/Desktop/FIFO_MiniZed/FIFO_MiniZed.srcs/sources_1/bd/PS_BRAM_BD/ip/PS_BRAM_BD_rst_ps7_0_50M_0/PS_BRAM_BD_rst_ps7_0_50M_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptsi/Desktop/FIFO_MiniZed/FIFO_MiniZed.srcs/sources_1/bd/PS_BRAM_BD/ip/PS_BRAM_BD_rst_ps7_0_50M_0/PS_BRAM_BD_rst_ps7_0_50M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptsi/Desktop/FIFO_MiniZed/FIFO_MiniZed.srcs/sources_1/bd/PS_BRAM_BD/ip/PS_BRAM_BD_auto_pc_0/PS_BRAM_BD_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptsi/Desktop/FIFO_MiniZed/FIFO_MiniZed.srcs/sources_1/bd/PS_BRAM_BD/ip/PS_BRAM_BD_auto_pc_1/PS_BRAM_BD_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Users/aptsi/Desktop/FIFO_MiniZed/FIFO_MiniZed.srcs/sources_1/bd/PS_BRAM_BD/PS_BRAM_BD_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/aptsi/Desktop/FIFO_MiniZed/FIFO_MiniZed.srcs/constrs_1/new/MiniZed_constraints.xdc
set_property used_in_implementation false [get_files C:/Users/aptsi/Desktop/FIFO_MiniZed/FIFO_MiniZed.srcs/constrs_1/new/MiniZed_constraints.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top FIFO -part xc7z007sclg225-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef FIFO.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file FIFO_utilization_synth.rpt -pb FIFO_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
