# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/aptsi/Desktop/FIFO_MiniZed/FIFO_MiniZed.srcs/sources_1/bd/PL_BRAM_BD/ip/PL_BRAM_BD_processing_system7_0_0/PL_BRAM_BD_processing_system7_0_0.xci
# IP: The module: 'PL_BRAM_BD_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/aptsi/Desktop/FIFO_MiniZed/FIFO_MiniZed.srcs/sources_1/bd/PL_BRAM_BD/ip/PL_BRAM_BD_processing_system7_0_0/PL_BRAM_BD_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'PL_BRAM_BD_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/Users/aptsi/Desktop/FIFO_MiniZed/FIFO_MiniZed.srcs/sources_1/bd/PL_BRAM_BD/ip/PL_BRAM_BD_processing_system7_0_0/PL_BRAM_BD_processing_system7_0_0.xci
# IP: The module: 'PL_BRAM_BD_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/aptsi/Desktop/FIFO_MiniZed/FIFO_MiniZed.srcs/sources_1/bd/PL_BRAM_BD/ip/PL_BRAM_BD_processing_system7_0_0/PL_BRAM_BD_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'PL_BRAM_BD_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
